name: Node.js CI/CD Pipeline  # 工作流名

on:                           # 触发器，定义何时运行此工作流
  push:
    branches: [main]          # 默认分支名!
    tags: ['**']              # or tags: ['v*']
  pull_request:
    branches: [main]
  workflow_dispatch:          # 手动执行

jobs:                         # 工作流
  build-obsidian:             # 作业 - ob构建部分
    runs-on: ubuntu-latest    # 环境 - 基于镜像
    steps:                    # 作业步骤！(name是可选的，但我都加上了方便调试和修改)
    - name: checkout repo
      uses: actions/checkout@v4   # 检出代码
    - name: Install pnpm          # 安装pnpm (如果你的 package.json::packageManager 字段没有设置，
      uses: pnpm/action-setup@v4  #   则要在这里加上 with 版本)
      with:
        version: 10.10.0
    - name: env use node.js
      uses: actions/setup-node@v4 # 配置node环境
      with:
        node-version: '22'
        cache: pnpm
    - name: build
      run: |
        pnpm install --frozen-lockfile
        pnpm ob:build
    - name: upload build artifact
      if: always()                      # 即使之前的构建步骤失败，也会上载构建产物
      uses: actions/upload-artifact@v4  # 保存构建产物 (使用的是官方提供的action)
      with:
        name: obsidian-any-block        # 构建产物的名称
        path: |                         # 构建产物的路径
          manifest.json
          main.js
          styles.css

  build-obsidian-min:         # 作业 - ob构建部分 (min版)
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.10.0
    - name: env use node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: pnpm
    - name: pnpm ob:build-min
      run: |                  # [!code] min
        pnpm install --frozen-lockfile
        pnpm ob:build-min
        mv dist-min/main.js main.js
        mv dist-min/manifest.json manifest.json
    - name: upload build artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: obsidian-any-block-min
        path: |
          manifest.json
          main.js
          styles.css

  build-obsidian-pro:         # 作业 - ob pro构建部分
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.10.0
    - name: env use node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: pnpm
    - name: pro
      # working-directory: ./src/
      run: |
        git clone --depth 1 https://${{ secrets.AnyBlockPro_Repo }}@github.com/any-block/any-block-pro.git
        mv ./any-block-pro/src/CodeMirror/ ./src/CodeMirror/
        mv ./any-block-pro/src/Pro/ ./src/Pro/
      env:
        GH_TOKEN: ${{ secrets.AnyBlockPro_Repo }}
    - name: pnpm ob:build-pro
      run: |                  # [!code] pro
        pnpm install --frozen-lockfile
        pnpm ob:build-pro
        mv dist-pro/main.js main.js
        mv dist-pro/manifest.json manifest.json
    - name: upload build artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: obsidian-any-block-pro
        path: |
          manifest.json
          main.js
          styles.css

  build-app:                  # 作业 - app构建部分
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.10.0
    - name: env use node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: pnpm
    - name: pro
      # working-directory: ./src/
      run: |
        git clone --depth 1 https://${{ secrets.AnyBlockPro_Repo }}@github.com/any-block/any-block-pro.git
        mv ./any-block-pro/src/CodeMirror/ ./src/CodeMirror/
        mv ./any-block-pro/src/Pro/ ./src/Pro/
      env:
        GH_TOKEN: ${{ secrets.AnyBlockPro_Repo }}
    - name: Build
      run: |
        pnpm install --frozen-lockfile
        cd ./src/App/
        pnpm build
        > ./dist/.nojekyll
    - name: Build - Dist to Website Branch
      if: github.event_name != 'pull_request'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        # 这是文档部署到的分支名称
        branch: gh-pages
        folder: src/App/dist

  build-markdwonit:           # 作业 - markdown-it构建测试
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.10.0
    - name: env use node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: pnpm
    - name: Build
      run: |
        pnpm install --frozen-lockfile
        pnpm mdit:build
    # 快速迭代和慢迭代冲突问题
    # 使用tag触发还是package.json version触发 (后者较繁琐)
    # - name: Publish to npm
    #   if: startsWith(github.ref, 'refs/tags/')  # 仅当 tag 推送时执行
    #   run: pnpm publish -r --access public --no-git-checks
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # 暂时手动发布，主要是更新频率不好控制
    # - name: Publish to npm (自动忽略版本冲突)
    #   if: github.event_name != 'pull_request'  # 仅在 push 时发布
    #   run: |
    #     cd src/markdownit
    #     pnpm publish --access public --no-git-checks || echo "::warning::Publish failed (可能版本未变更)"
    #   env:
    #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    #   continue-on-error: true  # 关键配置：允许步骤失败但不中断工作流

  create-release:
    name: Create Release
    if: github.event_name == 'push' # 跳过PR
    needs: [build-obsidian, build-obsidian-min, build-obsidian-pro] # 需要等待相关 build job 都成功
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          # 将所有构建产物下载到 'dist' 目录
          # 这将创建 'dist/artifact1'、'dist/artifact2' 等子目录
          path: ./dist
      
      - name: List downloaded artifacts
        run: |
          echo "Listing contents of ./dist:"
          ls -R ./dist

      # 场景一：release 到正式版 tag
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/') # 有tag
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.AnyBlockPro_Repo }}
          # 'tag' 默认就是 github.ref_name (即你推送的 tag)，所以不用写
          name: 'Release ${{ github.ref_name }}' # Release 标题使用 tag 名
          body: |
            (en) For the update log, please visit https://lincdocs.github.io/AnyBlock/docs/en/CHANGELOG

            (zh) 更新日志详见: https://lincdocs.github.io/AnyBlock/docs/zh/CHANGELOG
          artifacts: |
            ./dist/obsidian-any-block/*
          generateReleaseNotes: false # 自动根据 commits 生成 release notes。此外，这里应该导向一个更新日志页
          prerelease: true # 是否预发布 (可以在release上修改该项，我就不判断tag是否beta结尾了)
          makeLatest: false  # 是否最后一个版本 (可以在release上修改该项，我就不判断tag是否beta结尾了)
          allowUpdates: true # 如果 tag 已存在，允许更新

      - name: Create Release - min
        if: startsWith(github.ref, 'refs/tags/') # 有tag
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.AnyBlockPro_Repo }}
          # 以下三个表示在其他仓库进行 release
          owner: any-block
          repo: obsidian-any-block-min
          tag: ${{ github.ref_name }} # 使用相同的 tag 名
          name: 'Release ${{ github.ref_name }}' # Release 标题使用 tag 名
          body: |
            (en) For the update log, please visit https://lincdocs.github.io/AnyBlock/docs/en/CHANGELOG

            (zh) 更新日志详见: https://lincdocs.github.io/AnyBlock/docs/zh/CHANGELOG
          artifacts: |
            ./dist/obsidian-any-block-min/*
          generateReleaseNotes: false # 非本仓库则可能没有相同的 commit 历史，建议关闭
          prerelease: true
          makeLatest: false
          allowUpdates: true

      - name: Create Release - pro
        if: startsWith(github.ref, 'refs/tags/') # 有tag
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.AnyBlockPro_Repo }}
          # 以下三个表示在其他仓库进行 release
          owner: any-block
          repo: obsidian-any-block-pro
          tag: ${{ github.ref_name }} # 使用相同的 tag 名
          name: 'Release ${{ github.ref_name }}' # Release 标题使用 tag 名
          body: |
            (en) For the update log, please visit https://lincdocs.github.io/AnyBlock/docs/en/CHANGELOG

            (zh) 更新日志详见: https://lincdocs.github.io/AnyBlock/docs/zh/CHANGELOG
          artifacts: |
            ./dist/obsidian-any-block-pro/*
          generateReleaseNotes: false # 非本仓库则可能没有相同的 commit 历史，建议关闭
          prerelease: true
          makeLatest: false
          allowUpdates: true

      # 场景二：release 到固定的 beta tag
      # 略
